### ISSUE TITLE
Provide instructions to run from the command line

### ISSUE THREAD

**Issue by greggles** [pwnsdx/BadCode#1]
This seems like an interesting tool.

I'd love to be able to integrate it into an automated nightly build process. Any tips for how to run the rules across a codebase from the command line?

**Comment by pwnsdx** [comment]
Hello,

Thanks! I wish I can make the CLI tool later but for now I'm working on the rules itself so if you want to do it, it would be awesome! :)

To use the rules you need a library to parse the Yaml file (alpha.yaml) and a way to iterates over the files of a user-provided folder.

Regards,

**Comment by ineedblood** [comment]
I'm working on an online proccesor of something alike, though your rules are apparently consuming too much

**Comment by greggles** [comment]
Thanks for the feedback - I'll see what I come up with.

**Comment by pwnsdx** [comment]
> I'm working on an online proccesor of something alike, though your rules are apparently consuming too much

It really depends, with Sublime Text I rarely got complexity error but don't worry I'm actively working on optimizing the rules!

**Comment by ineedblood** [comment]
@pwnsdx well in sublime with a single short file it goes well... but i'm running it through complete projects, efficiency is a must!

**Comment by pwnsdx** [comment]
Normally it should not. I tried many of these regexes against big projects like WHMCS and Magento and it works well for many of them. Again, I'm working on regexes optimization and I should commit the changes soon.
