### ISSUE TITLE
Buy a Sublime Text licence

### ISSUE THREAD

**Issue by phocean** [pwnsdx/BadCode#2]
Just saying... to show appreciation to the author for this great editor (and because the licence free agreement is just for testing).

**Comment by pwnsdx** [comment]
Hello,

Indeed, this software is good stuff but I use Atom, it's just that Atom is really bad for this task so I tried with different editors and ST is from far the best.

CLI tool is on the roadmap so there will be no more ST requirement.

I would buy every license in the world, if I had money.

> licence free agreement is just for testing

Well, I am just testing my regexes via Sublime Text, nothing bad :)

**Comment by phocean** [comment]
Ok, got it! Thanks for your reply and sharing your work :-)

**Comment by ineedblood** [comment]
I could provide the CLi editor since I did something of the like for the web application...

**Comment by pwnsdx** [comment]
Feel free to share it :)
